/**
 * Consumer meal catalog — synthetic library for plans (not ops snapshot IDs).
 */

export const MEALS = [
  {
    id: "meal-chipotle-tofu-tacos",
    slug: "crispy-chipotle-tofu-tacos",
    title: "Crispy Chipotle Tofu Tacos",
    subtitle: "Smoky, tangy · ~40 min",
    cuisine: "Mexican",
    effort: "moderate",
    format: "tacos",
    flavors: ["smoky", "spicy", "tangy"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
    },
    prepMin: 20,
    cookMin: 20,
    steps: [
      "Press and cube tofu; toss with oil, cornstarch, and spices.",
      "Air fry at 400°F 14–18 min until crisp, shaking halfway.",
      "Toss cabbage slaw with lime, oil, and cilantro; rest 5 min.",
      "Warm tortillas; build tacos with tofu, slaw, and avocado.",
    ],
    ingredients: [
      "Extra-firm tofu, corn tortillas, cabbage, chipotle, lime, avocado",
    ],
  },
  {
    id: "meal-coconut-chickpea-curry",
    slug: "coconut-chickpea-spinach-curry",
    title: "Coconut Chickpea & Spinach Curry",
    subtitle: "Creamy, aromatic · ~40 min",
    cuisine: "Indian-inspired",
    effort: "easy",
    format: "curry",
    flavors: ["aromatic", "creamy", "mild spice"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
    },
    prepMin: 15,
    cookMin: 25,
    steps: [
      "Sauté onion, garlic, and ginger; bloom curry spices.",
      "Simmer chickpeas in coconut milk 12–15 min; mash a few for body.",
      "Fold in spinach until wilted; finish with lime and salt.",
      "Serve over basmati rice.",
    ],
    ingredients: ["Chickpeas, coconut milk, spinach, basmati, curry spices"],
  },
  {
    id: "meal-white-bean-rigatoni",
    slug: "tomato-basil-white-bean-rigatoni",
    title: "Tomato-Basil White Bean Rigatoni",
    subtitle: "Bright, herby · ~35 min",
    cuisine: "Italian",
    effort: "easy",
    format: "pasta",
    flavors: ["savory", "herby", "bright"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
    },
    prepMin: 10,
    cookMin: 25,
    steps: [
      "Cook rigatoni until just shy of al dente; reserve pasta water.",
      "Sauté garlic; simmer tomatoes with oregano.",
      "Add beans; mash some for a creamy sauce without dairy.",
      "Toss pasta with sauce, basil, and olive oil.",
    ],
    ingredients: ["Rigatoni, cannellini beans, tomato, garlic, basil"],
  },
  {
    id: "meal-miso-salmon",
    slug: "blackstone-miso-ginger-salmon",
    title: "Miso-Ginger Salmon with Bok Choy",
    subtitle: "Umami, garlicky · ~35 min",
    cuisine: "Japanese-inspired",
    effort: "moderate",
    format: "plated",
    flavors: ["umami", "savory"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
      contains_fish: true,
    },
    prepMin: 15,
    cookMin: 20,
    steps: [
      "Cook jasmine rice.",
      "Whisk miso glaze; coat salmon fillets.",
      "Sear salmon skin-side down until crisp; flip briefly.",
      "Blister bok choy cut-side down; plate with rice.",
    ],
    ingredients: ["Salmon, miso, bok choy, jasmine rice, ginger, garlic"],
  },
  {
    id: "meal-lemon-dill-cod",
    slug: "sheet-pan-lemon-dill-cod",
    title: "Sheet-Pan Lemon-Dill Cod",
    subtitle: "Bright, herby · ~45 min",
    cuisine: "Mediterranean",
    effort: "easy",
    format: "sheet-pan",
    flavors: ["bright", "citrus", "herby"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
      contains_fish: true,
    },
    prepMin: 15,
    cookMin: 30,
    steps: [
      "Roast potatoes with oil and spices 15 min at 425°F.",
      "Coat cod with lemon-dill mixture.",
      "Add green beans and cod to the sheet; roast 12–15 min more.",
      "Serve with extra lemon.",
    ],
    ingredients: ["Cod, baby potatoes, green beans, lemon, dill"],
  },
  {
    id: "meal-shiitake-bowls",
    slug: "blackstone-ginger-shiitake-broccoli-bowls",
    title: "Ginger Shiitake Broccoli Bowls",
    subtitle: "Charred, umami · ~35 min",
    cuisine: "Chinese-inspired",
    effort: "moderate",
    format: "bowl",
    flavors: ["savory", "gingery"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
    },
    prepMin: 15,
    cookMin: 20,
    steps: [
      "Cook jasmine rice.",
      "Char broccoli on high heat until tender-crisp.",
      "Brown shiitakes; add garlic, ginger, and sauce.",
      "Bowl rice and vegetables; finish with scallions and lime.",
    ],
    ingredients: ["Broccoli, shiitake, jasmine rice, soy, ginger, scallions"],
  },
  {
    id: "meal-lentil-tagine",
    slug: "moroccan-lentil-carrot-tagine",
    title: "Lentil & Roasted Carrot Tagine",
    subtitle: "Warm-spiced · ~45 min",
    cuisine: "Moroccan-inspired",
    effort: "easy",
    format: "stew",
    flavors: ["warm-spiced", "savory"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
    },
    prepMin: 15,
    cookMin: 30,
    steps: [
      "Roast spiced carrots until caramelized.",
      "Simmer lentils with onion, spices, and tomatoes until tender.",
      "Steam couscous; fluff with olive oil.",
      "Stir carrots and lemon into stew; serve over couscous.",
    ],
    ingredients: ["Lentils, carrots, couscous, warm spices, cilantro"],
  },
  {
    id: "meal-falafel-wraps",
    slug: "crispy-falafel-pita-wraps",
    title: "Crispy Falafel Wraps",
    subtitle: "Herby, tangy · ~40 min · contains cashews",
    cuisine: "Middle Eastern",
    effort: "moderate",
    format: "wraps",
    flavors: ["herby", "tangy", "savory"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: true,
      cashews_only: true,
    },
    prepMin: 20,
    cookMin: 20,
    steps: [
      "Pulse chickpeas with herbs and spices; form patties.",
      "Air fry falafel until deep golden.",
      "Blend soaked cashews with tahini and lemon for sauce.",
      "Fill warm pitas with salad, falafel, and sauce.",
    ],
    ingredients: ["Chickpeas, pita, cucumber, cashews, tahini, herbs"],
  },
  {
    id: "meal-gochujang-trout",
    slug: "blackstone-gochujang-trout",
    title: "Gochujang-Glazed Trout",
    subtitle: "Sweet-heat · ~35 min",
    cuisine: "Korean-inspired",
    effort: "moderate",
    format: "plated",
    flavors: ["sweet-heat", "savory"],
    dietFlags: {
      contains_dairy: false,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
      contains_fish: true,
    },
    prepMin: 15,
    cookMin: 20,
    steps: [
      "Cook rice; prep sesame cucumber salad.",
      "Whisk gochujang glaze; coat trout.",
      "Sear trout skin-side down; flip briefly and glaze.",
      "Plate with rice, salad, and scallions.",
    ],
    ingredients: ["Trout, gochujang, cucumber, rice, scallions"],
  },
  /** Gate test meals — never shown unless we demo rejection internally */
  {
    id: "meal-demo-reject-dairy",
    slug: "_reject_dairy",
    title: "Creamy Alfredo Penne (demo reject)",
    subtitle: "Contains dairy — eligibility stub",
    cuisine: "Italian",
    effort: "easy",
    format: "pasta",
    flavors: ["rich"],
    dietFlags: {
      contains_dairy: true,
      contains_shellfish: false,
      contains_meat_non_fish: false,
      contains_poultry: false,
      contains_nuts: false,
      cashews_only: false,
    },
    prepMin: 10,
    cookMin: 15,
    steps: ["Demo only."],
    ingredients: ["Pasta, cream, parmesan"],
    hidden: true,
  },
];

export function getMealById(id) {
  return MEALS.find((m) => m.id === id) || null;
}

export function getVisibleMeals() {
  return MEALS.filter((m) => !m.hidden);
}
